// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcdpverffffivoxroytr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZHB2ZXJmZmZmaXZveHJveXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMDM0OTEsImV4cCI6MjA4ODU3OTQ5MX0.zZo798whEZuQQxuw9uqZGieTRJKRPHLZS7if1JPgQkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Untyped client for tables/columns not yet in generated types
// Use: import { supabaseUntyped } from "@/integrations/supabase/client";
export const supabaseUntyped = supabase as any;